# golangをビルド用イメージとして使うパターン
FROM golang:1.13
COPY . ./goapp
WORKDIR ./goapp

# ビルド時にクロスコンパイルのオプションを指定
RUN go mod download && \
    CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /app .

# ベースイメージはalpineを指定
FROM alpine:latest
LABEL maintainer="usimihsr"
WORKDIR goapp

# ビルド用イメージからバイナリをコピー
COPY --from=0 /app ./

# httpsで通信するのに必要なCA証明書を用意する
RUN apk --no-cache add ca-certificates

ENTRYPOINT ["./app"]
